# Generated by Django 4.1 on 2024-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='portfolio/covers/%y/%m/%d/'),
        ),
    ]
